# Streamlit Secrets Configuration
# This file contains configuration secrets for the Streamlit UI

# API Configuration
API_URL = "http://localhost:8000"

# You can add other secrets here as needed
# For example:
# DATABASE_URL = "your_database_url_here"
# SECRET_KEY = "your_secret_key_here" 